title: The title here, ya know
author: some github user, ya know
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  awesome description here....

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
